parameters:
#    stepiiik_zfmeetup.example.class: Stepiiik\ZfmeetupBundle\Example

services:
#    stepiiik_zfmeetup.example:
#        class: %stepiiik_zfmeetup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
