services:

  controller.album_controller:
    class: Stepiiik\ZfmeetupBundle\Controller\AlbumController

  controller.default_controller:
    class: Stepiiik\ZfmeetupBundle\Controller\DefaultController

  controller.security_controller:
    class: Stepiiik\ZfmeetupBundle\Controller\SecurityController

  repository.album_repository:
    class: Stepiiik\ZfmeetupBundle\Repository\AlbumRepository
    arguments: [@doctrine.orm.default_entity_manager]